sudo: false

os:
  - linux

language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    - ubuntu-sdk-team
    packages:
    - gcc-5
    - g++-5
    - qtbase5-dev
    - qtdeclarative5-dev
    - libqt5webkit5-dev
    - libsqlite3-dev
    - qt5-default
    - qttools5-dev-tools

before_install:
  - pwd
  - wget --no-check-certificate https://cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=`pwd`/cmake-3.2.3-Linux-x86_64/bin:$PATH
  - export CC=gcc-5 CXX=g++-5
  - wget https://github.com/grzegorzmazur/yacas/archive/master.zip
  - unzip master.zip
  - cd yacas-master
  - mkdir install
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../install ..
  - make
  - make install
  - cd ../..
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DYACAS_PREFIX=../yacas-master/install ..

script:
  - make VERBOSE=1
