sudo: false

os:
  - linux

language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-ppa-backports
    packages:
    - gcc-5
    - g++-5
    - cmake

before_install:
  - pwd
  - export CC=gcc-5 CXX=g++-5
  - wget https://github.com/grzegorzmazur/yacas/archive/master.zip
  - unzip master.zip
  - cd yacas-master
  - mkdir install
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../install ..
  - make
  - make install
  - cd ../..
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DYACAS_PREFIX=../yacas-master/install ..

script:
  - make
