os:
  - linux

language: cpp

before_install:
  - pwd
  - wget --no-check-certificate https://cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=`pwd`/cmake-3.2.3-Linux-x86_64/bin:$PATH
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:beineri/opt-qt542
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 qt54base qt54tools qt54svg qt54webkit
  - export CXX=g++-4.8
  - export CC=gcc-4.8
  - wget https://github.com/grzegorzmazur/yacas/archive/master.zip
  - unzip master.zip
  - cd yacas-master
  - mkdir install
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../install -DCMAKE_PREFIX_PATH=/opt/qt54/lib/cmake ..
  - make
  - make install
  - cd ../..
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DYACAS_PREFIX=../yacas-master/install ..

script:
  - make VERBOSE=1
